FROM python:3.10.13

WORKDIR /app
ARG TARGET_BRANCH
ARG GIT_TOKEN
ENV DEPLOYMENT=local

RUN apt-get update && apt-get upgrade -y \
&& apt-get -y install git libgl1-mesa-dev \
&& git clone https://github.com/toposoid/toposoid-language-detector-web.git \
&& cd toposoid-language-detector-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sed -i s/__##GIT_TOKEN##__/${GIT_TOKEN}/g requirements.txt \
&& pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt
