name: Test And Build
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-language-detector-web
  PJ_BRANCH: main
  PJ_VERSION: 0.6
jobs:
  unit-test_toposoid-language-detector-web:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            sed -i s/__##GIT_TOKEN##__/${{ secrets.GIT_TOKEN }}/g requirements.txt
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            sed -i s/__##YOUR_ADOBE_PDF_SERVICES_CLIENT_ID##__/${{ secrets.ADOBE_PDF_SERVICES_CLIENT_ID }}/g docker-compose-workflow.yml
            sed -i s/__##YOUR_ADOBE_PDF_SERVICES_CLIENT_SECRET##__/${{ secrets.ADOBE_PDF_SERVICES_CLIENT_SECRET }}/g docker-compose-workflow.yml            
            docker compose -f docker-compose-workflow.yml up -d            
            docker compose logs
            sleep 10
            echo 'quit' | curl -s -o /dev/null telnet://localhost:3306
            docker compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && pytest -v"            
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
